### ISSUE TITLE
Insane amount of duplicate textures

### ISSUE THREAD

**Issue by Napiophelios** [TumeniNodes/artdeco#1]
You are using way too many duplicate textures.

You can reduce from 200+ textures to about 70 if you just reuse the images
instead of renaming the same image for the node you are registering.

You can also use texture modifiers to reduce it even more if you wanted to.

Beautiful artwork btw.

**Comment by TumeniNodes** [comment]
I had not even thought about that, you're right.
I can use the same image for all of the bottom, sides etc., as you suggest.
Never even crossed my mind, thank you
And thanks for the compliment

**Comment by TumeniNodes** [comment]
closing this for now.
Will address this issue eventually. Not a top priority atm
